### ISSUE TITLE
Absolute function - b=abs(a)

### ISSUE THREAD

**Issue by Wardergrip** [samynk/VecMath#12]
Perhaps `|` should be repurposed as abs and `||` used as length of symbol.

I think either way `abs()` and `length()` would be clear and prevent mistakes from happening.

**Comment by samynk** [comment]
abs should definitely be a function, can also be used to create a vector will positive components. The || symbols can definitely be confusing, but are sometimes powerful to create shorter expressions. But a function to calculate the magnitude or norm would be useful as well, will probably call it norm or magnitude or mag.

**Comment by samynk** [comment]
Closed, implemented.
