### ISSUE TITLE
Length of a variable that is 0 results in -nan(ind)

### ISSUE THREAD

**Issue by Wardergrip** [samynk/VecMath#14]
```xml
<vecmath>clear
<vecmath>c=a.b
<vecmath>print c
c = [0]
<vecmath>d=con(c)/(|c|*|c|)
<vecmath>print d
d = [-nan(ind)]
```

**Comment by Wardergrip** [comment]
To make sure the `|0|` is the one getting this undefined behaviour, I tested it seperately.

Dividing by 0 results in `inf` which is fine (I think)

**Comment by samynk** [comment]
the con(c) , in other words the conjugate of a scaler returns [-nan(ind)], maybe it should just leave the value as it is, since a scalar does not have imaginary components.

**Comment by samynk** [comment]
The result of 0/0 in C++ (and most programming languages) is NaN. Behaviour of conjugate was made more friendly by just doing nothing for variables that do not have an imaginary part. Closing.
