### ISSUE TITLE
Running the documentation site.

### ISSUE THREAD

**Issue by SixArne** [samynk/VecMath#25]
To put the documentation online on Github you have to install NVM and install version 16.15.0 .
https://github.com/coreybutler/nvm-windows

Once nvm is installed you can run 
(You might have to use the nvm command in administrator mode)

```nvm install 16.15.0``` 
```nvm use 16.15.0```

After that you run deploy.sh and it should handle the rest automatically.

**Comment by samynk** [comment]
Problems running the deploy.sh, moved to 1.0.5

**Comment by samynk** [comment]
Solved the authentication issue that was given 'permission denied' errors when pushing the pages.
