### ISSUE TITLE
Faulty error message: missing ')'

### ISSUE THREAD

**Issue by Wardergrip** [samynk/VecMath#27]
![image](https://user-images.githubusercontent.com/42802496/167631970-150fbb66-e2b4-4619-8f44-9741c1eccb90.png)

The highlighted charachter is not at fault. The describing error message also does not illustrate the mistake that happend.
What I did wrong is I missed a `)` with the `sin`

**Comment by samynk** [comment]
There is an extra check for unbalanced parentheses and brackets now, closing for now but opening discussion about error messages to gather all info.
