### ISSUE TITLE
Get Vector from quarternion

### ISSUE THREAD

**Issue by gaslam** [samynk/VecMath#34]
Not sure if this was mentioned already, but that would be a handy feature. It should not be that difficult to implement

**Comment by samynk** [comment]
Do you mean getting the actual rotation axis or getting the  current x,y,z values?

**Comment by gaslam** [comment]
The current x,y,z values.
Let's say I have an exercise where one of the given quarternions is [2,(3,4,5)] I want the vector (3,4,5).

**Comment by samynk** [comment]
ah okay, not so hard to implement just need to think carefully about syntax.
