### ISSUE TITLE
Angled and angle bug??

### ISSUE THREAD

**Issue by SixArne** [samynk/VecMath#48]
Expected behaviour:

```cpp
p = [1.2, (1.2, 1.2, 1.2)]
angled(p)

[60]
```

Current behaviour:

```cpp
p = [1.2, (1.2, 1.2, 1.2)]
angled(p)

[-nan(ind)]
```

Maybe I am wrong, but I expect the program to calculate the angle with the following formula:

```cpp
acosd(re(p)/norm(p))
```

**Comment by samynk** [comment]
The angled and angle function work only on normalized quaternions, maybe I can add a normalization step before calculating the angle.
