### ISSUE TITLE
Implement proper quaternion multiplication

### ISSUE THREAD

**Issue by LuckyLuke00** [samynk/VecMath#56]
I don't know if this is on purpose, but there seems to be no easy way to do a proper quaternion multiplication.

When you multiply two or more quaternions, for example:

```
q1 = [1 , ( 0 , 0 , 1 )]
q2 = [2 , ( 0 , 0 , 2 )]

q = q1 * q2
```

You get:

```
q = [2 ,( 0 , 0 , 2 )]
```

Instead of:

```
q = [0 ,( 0 , 0 , 4 )]
```

A way to implement this would be:

```
w = w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2
x = w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2
y = w1 * y2 + y1 * w2 + z1 * x2 - x1 * z2
z = w1 * z2 + z1 * w2 + x1 * y2 - y1 * x2
```

**Comment by samynk** [comment]
The * operator is a hadamard operator (meaning element wise multiplication), you can multiply quaternions with the '. ' operator.

**Comment by LuckyLuke00** [comment]
Great! Thanks for the quick response and clarification.
