### ISSUE TITLE
Issue when subtracting negative numbers.

### ISSUE THREAD

**Issue by LuckyLuke00** [samynk/VecMath#57]
There seems to be a bug when subtracting from a negative number.

When I type in:
`-0.689442 - 0.84265`

it gives the result:
`[0.153208]`

when it should be:
`[-0.153208]`

**Comment by samynk** [comment]
Thank you for reporting this, I will add this issue for the next release.

**Comment by samynk** [comment]
Fixed, was priority issue with the unary operator
