### ISSUE TITLE
loop error

### ISSUE THREAD

**Issue by CrazyMonkey-jj** [samynk/VecMath#6]
the bugg part:

vecmath>a=[1,-(2,3,4)]
line 1:8 missing ')' at ','
line 1:12 extraneous input ')' expecting {']', ','}
I do not know 'a'
If you meant this as a command, this is a command I do not understand.
Type 'help' for a list of commands.
If you want this to be a variable you need the following format: b = 7

after bug is activated

vecmath>b = 7
I do not know 'a'
If you meant this as a command, this is a command I do not understand.
Type 'help' for a list of commands.
If you want this to be a variable you need the following format: b = 7

dad joke:

why do bugs show up with beginner programmers:
light mode atracks the bugs

**Comment by samynk** [comment]
Fixed, expression stack is now cleared after every line, ensuring that errors in one operation do not spill over to the next line. Thanks for reporting and documenting it so clearly.
